# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

schedules:
- cron: 0 0 1 * *
  displayName: Monthly 1st day midnight build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: './BuildPackage.ps1'
    pwsh: true

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '/src/Jiguang.JPush.Extensions/bin/Release/Jiguang.JPush.Extensions.*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget1'